baseURL: 'https://htwoo.io/'
languageCode: 'en-us'
title: 'hTWOo'

theme: 'h2o'

services:
  googleAnalytics:
    id: G-279ZFL8MMG

relativeURLs: true
canonifyURLs: true

disableKinds:
- taxonomy
- term

params:
  seoTitle: 'hTWOo by N8D'
  siteDescription: "hTWOo is a set of Fluent Design UI components and utilities resulting from an effort to converge the set of HTML and ReactJS based component libraries."
  author: "Stefan Bauer / N8D"
  github: "https://github.com/stfbauer"
  facebook: "https://www.facebook.com/n8dstudio"
  ogimage: "/images/launch-img.jpg"
  sitename: "hTWOo by N8D"
  twitter: "@stfbauer"
  dateFormat: "January 2, 2006"
  localSVGPath: "static"
  
# enable full markup
# markup:
#   goldemark:
#     renderer:
#       unsafe: true
#     parser:
#       wrapStandAloneImageWithinParagraph: false

mount:
  - source: static
    target: static
markup:
  goldmark:
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: false
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false      
